# Generated by Django 6.0.7 on 2026-08-05 10:19

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Model id as the gateway exposes it", max_length=128, unique=True
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("provider", models.CharField(blank=True, max_length=64)),
                (
                    "input_price_per_million",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Price per 1,000,000 input tokens, in the installation currency",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "output_price_per_million",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Price per 1,000,000 output tokens, in the installation currency",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
