# Generated by Django 6.0.7 on 2026-08-10 02:52

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    """What a prompt cache costs on this model (`FRD-133`).

    Two rates rather than a multiplier: the vendors do not agree on one. Null means "charge the
    ordinary input rate", deliberately not "free" — `FRD-403`'s rule about unpriced traffic,
    applied one field in.
    """

    dependencies = [
        ("catalog", "0003_model_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="cache_write_price_per_million",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text=(
                    "Price per 1,000,000 input tokens written into the provider's prompt cache"
                ),
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="cached_input_price_per_million",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text=(
                    "Price per 1,000,000 input tokens served from the provider's prompt cache"
                ),
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
