# Generated by Django 6.0.7 on 2026-08-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_regions_are_a_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="context_window",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
