# Generated by Django 6.0.7 on 2026-08-12 17:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("outbox", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="outboxevent",
            options={"ordering": ["created_at", "id"]},
        ),
    ]
