# Generated by Django 6.0.7 on 2026-08-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apikeys", "0002_apikey_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="issued_by",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
