# Generated by Django 6.0.7 on 2026-08-04 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("usecases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("steps", models.JSONField(default=list)),
                ("fallback_models", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "use_case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline",
                        to="usecases.usecase",
                    ),
                ),
            ],
        ),
    ]
