# Generated by Django 6.0.7 on 2026-08-05 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usecases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usecase",
            name="retention_days",
            field=models.PositiveSmallIntegerField(
                default=7,
                help_text="Days that stored prompts and responses are kept. Metadata is retained.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3650),
                ],
            ),
        ),
    ]
