# Generated by Django 6.0.7 on 2026-08-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usecases", "0002_usecase_retention_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="usecase",
            name="store_payloads",
            field=models.BooleanField(
                default=True,
                help_text="Store prompts and responses at all. Off means nothing is written.",
            ),
        ),
    ]
