# Generated by Django 6.0.7 on 2026-08-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usecases", "0004_usecasegroupgrant"),
    ]

    operations = [
        migrations.AddField(
            model_name="usecase",
            name="tools_enabled",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Let this use case declare functions for the model to call "
                    "(FRD-131). Off by default."
                ),
            ),
        ),
    ]
