# Generated by Django 6.0.7 on 2026-08-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usecases", "0005_usecase_tools_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="usecase",
            name="restrict_members_to_own_requests",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Show each use-case *user* only the requests they made themselves. An "
                    "administrator of the use case still sees all of them. Default off, which is "
                    "the behaviour that already existed — this is a restriction an administrator "
                    "may impose, not a permission that was previously assumed."
                ),
            ),
        ),
        migrations.AlterField(
            model_name="usecase",
            name="tools_enabled",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Let this use case declare functions for the model to call (FRD-131). Off by "
                    "default: a use case that summarises documents has no business declaring "
                    "functions, and the smallest set that needs tool calling is the right set to "
                    "have it."
                ),
            ),
        ),
    ]
