# Generated by Django 6.0.7 on 2026-08-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usecases", "0006_usecase_restrict_members_to_own_requests_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usecase",
            name="prompt_caching_enabled",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Let the gateway mark this use case's stable prefix — tool "
                    "declarations and system instruction — as cacheable at the provider "
                    "(FRD-133). Off by default: on Vertex the cache scope is the whole "
                    "organisation, so a use case whose system prompt is itself "
                    "confidential should not be opted in by somebody else's cost "
                    "decision."
                ),
            ),
        ),
    ]
