# Generated by Django 6.0.7 on 2026-08-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usecases", "0007_prompt_caching"),
    ]

    operations = [
        migrations.AddField(
            model_name="usecase",
            name="prompt_cache_ttl",
            field=models.CharField(
                choices=[("5m", "5 minutes"), ("1h", "1 hour")],
                default="5m",
                help_text=(
                    "How long the provider should keep this use case's cached prefix "
                    "(FRD-133). The trade-off is real and only measurement settles it: "
                    "an hour costs about twice the ordinary input price to write "
                    "against roughly a quarter extra for five minutes, and pays for "
                    "itself only if the gap between turns regularly exceeds five "
                    "minutes."
                ),
                max_length=4,
            ),
        ),
    ]
