# Generated by Django 6.0.7 on 2026-08-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_cache_prices"),
        ("usecases", "0008_prompt_cache_ttl"),
    ]

    operations = [
        migrations.AddField(
            model_name="usecase",
            name="allowed_models",
            field=models.ManyToManyField(
                blank=True,
                help_text=(
                    "The models this use case may call (FRD-308). Empty means none: "
                    "a model is released for a use case, never assumed."
                ),
                related_name="use_cases",
                to="catalog.model",
            ),
        ),
    ]
