# Generated by Django 6.0.7 on 2026-08-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usecases", "0011_alter_usecase_allowed_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="usecase",
            name="include_reasoning",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Return the model's reasoning to callers and store it with the "
                    "answer (FRD-135). Off by default: reasoning can restate the "
                    "prompt verbatim."
                ),
            ),
        ),
    ]
