# Generated by Django 6.0.7 on 2026-08-04 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("usecases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("use_case", "Use case"), ("member", "Member")], max_length=16
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255)),
                (
                    "period",
                    models.CharField(
                        choices=[("day", "Daily"), ("month", "Monthly")],
                        default="month",
                        max_length=8,
                    ),
                ),
                ("limit_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("limit_requests", models.PositiveIntegerField(blank=True, null=True)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "use_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="usecases.usecase",
                    ),
                ),
            ],
            options={
                "ordering": ["scope", "subject"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("use_case", "scope", "subject", "period"), name="uq_budget"
                    )
                ],
            },
        ),
    ]
