# Generated by Django 6.0.7 on 2026-08-05 10:19

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budgets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="limit_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Spend limit for the period, in the installation currency",
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
