# Generated by Django 6.0.7 on 2026-08-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budgets", "0002_budget_limit_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="scope",
            field=models.CharField(
                choices=[
                    ("use_case", "Use case"),
                    ("each_member", "Each member"),
                    ("member", "One member"),
                ],
                max_length=16,
            ),
        ),
    ]
