# Generated by Django 6.0.7 on 2026-08-20 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """A budget may belong to the installation rather than to a use case (`FRD-610`).

    Nothing is backfilled and nothing needs to be: every existing row names a use case, which is
    what the check constraint requires of every non-installation scope. What the migration adds is
    the *possibility* of a row that names none — and the two constraints that stop that possibility
    from becoming a hole:

    - `uq_installation_budget` because a NULL is not equal to itself in SQL, so `uq_budget` stops
      policing exactly the rows this feature introduces: two installation budgets for one period
      would both be accepted and the gateway would enforce whichever it read first.
    - `ck_budget_scope_matches_owner` because `clean()` runs for a form and not for a fixture, a
      shell or a migration, and a row whose scope says *installation* while naming a use case is a
      budget matched against traffic nobody meant.
    """

    dependencies = [
        ("budgets", "0004_drop_member_scope"),
        ("usecases", "0013_soft_delete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="scope",
            field=models.CharField(
                choices=[
                    ("use_case", "Use case"),
                    ("each_member", "Each member"),
                    ("installation", "Installation"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="use_case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budgets",
                to="usecases.usecase",
            ),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.UniqueConstraint(
                condition=models.Q(("use_case__isnull", True)),
                fields=("scope", "period"),
                name="uq_installation_budget",
            ),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("scope", "installation"), ("use_case__isnull", True)),
                    models.Q(
                        models.Q(("scope", "installation"), _negated=True),
                        ("use_case__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ck_budget_scope_matches_owner",
            ),
        ),
    ]
