# Generated by Django 6.0.7 on 2026-08-05 13:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("usecases", "0003_usecase_store_payloads"),
    ]

    operations = [
        migrations.CreateModel(
            name="RateLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("use_case", "Use case"), ("member", "Member")], max_length=16
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255)),
                (
                    "limit_rpm",
                    models.PositiveIntegerField(
                        help_text="Sustained requests per minute",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000000),
                        ],
                    ),
                ),
                (
                    "burst",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Requests allowed at once; 0 uses the per-minute limit",
                        validators=[django.core.validators.MaxValueValidator(1000000)],
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "use_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_limits",
                        to="usecases.usecase",
                    ),
                ),
            ],
            options={
                "ordering": ["scope", "subject"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("use_case", "scope", "subject"), name="uq_rate_limit"
                    )
                ],
            },
        ),
    ]
