# Generated by Django 6.0.7 on 2026-08-07 14:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import aira_common.anomalies


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("usecases", "0003_usecase_store_payloads"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnomalyRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("refusal_rate", "refusal_rate"),
                            ("error_rate", "error_rate"),
                            ("spend_spike", "spend_spike"),
                            ("request_spike", "request_spike"),
                            ("new_source_ip", "new_source_ip"),
                            ("payload_size", "payload_size"),
                            ("blocked_prompt_rate", "blocked_prompt_rate"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "window_minutes",
                    models.PositiveIntegerField(
                        default=15,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1440),
                        ],
                    ),
                ),
                (
                    "threshold",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("min_sample", models.PositiveIntegerField(default=20)),
                (
                    "action",
                    models.CharField(
                        choices=[("alert", "alert"), ("throttle", "throttle"), ("block", "block")],
                        default=aira_common.anomalies.RuleAction["ALERT"],
                        max_length=16,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("subject", "subject"),
                            ("credential", "credential"),
                            ("use_case", "use_case"),
                        ],
                        default=aira_common.anomalies.RuleTarget["SUBJECT"],
                        max_length=16,
                    ),
                ),
                (
                    "action_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10080),
                        ],
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "use_case",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empty means the rule applies everywhere.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomaly_rules",
                        to="usecases.usecase",
                    ),
                ),
            ],
            options={
                "ordering": ["use_case_id", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("use_case__isnull", False)),
                        fields=("use_case", "name"),
                        name="uq_anomaly_rule_name",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("use_case__isnull", True)),
                        fields=("name",),
                        name="uq_global_anomaly_rule_name",
                    ),
                ],
            },
        ),
    ]
