# Generated by Django 6.0.7 on 2026-08-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anomalies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="anomalyrule",
            name="parameter",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
