# Generated by Django 6.0.7 on 2026-08-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anomalies", "0002_anomalyrule_parameter"),
    ]

    operations = [
        migrations.AddField(
            model_name="anomalyrule",
            name="throttle_rpm",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
