"""Generate `docs/features/README.md` from the FRDs themselves.

**Why generated rather than written.** Feature status was kept in two places — each FRD's header
and a prose section of `CLAUDE.md` — and on 2026-08-13 twenty-two of them disagreed: `FRD-100`,
the Gemini surface every request goes through, still said *Draft*, as did tool calling, the whole
of Phase 0 and most of Phase 2. The copy that is read every session stayed true and the copy
nobody opens rotted, which is this repository's oldest defect shape wearing documentation.

So the FRD header is the single source, and this reads it. Regenerating is the check:
`tools/tests/test_features_index.py` fails when the committed index differs from what the headers
say, which catches a status changed without the index and an FRD added without either.

    uv run python tools/features_index.py            # print
    uv run python tools/features_index.py --write    # rewrite docs/features/README.md
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FEATURES = ROOT / "docs" / "features"
INDEX = FEATURES / "README.md"

#: `# FRD-123 — Title`
_TITLE = re.compile(r"^#\s+FRD-(\d+)\s+[—-]\s+(.+?)\s*$", re.MULTILINE)
#: `> Phase: 3 · Status: **Built (2026-08-11)** · Owner: …`
_PHASE = re.compile(r"Phase:\s*([^·\n]+?)\s*·")
_STATUS = re.compile(r"Status:\s*\*\*(.+?)\*\*")

#: What a status has to start with to count as delivered. Deliberately a **prefix** match on a
#: short list rather than a keyword search: "Draft — optional, and probably should not be built
#: first" contains the word "built".
_DELIVERED = ("done", "built", "implemented", "stage a done", "both stages done")


@dataclass(frozen=True, slots=True)
class Feature:
    number: str
    title: str
    phase: str
    status: str
    path: str

    @property
    def delivered(self) -> bool:
        return self.status.lower().startswith(_DELIVERED)


def read() -> list[Feature]:
    """Every FRD, in number order. The template is not one."""
    features: list[Feature] = []
    for path in sorted(FEATURES.glob("FRD-*.md")):
        if path.stem == "FRD-TEMPLATE":
            continue
        text = path.read_text()
        title = _TITLE.search(text)
        phase = _PHASE.search(text)
        status = _STATUS.search(text)
        if not (title and status):
            raise SystemExit(
                f"{path.name}: no parseable `# FRD-NNN — Title` and `Status: **…**` header. "
                "The header is the single source of a feature's status — an FRD without one is "
                "invisible to every reader who does not open it."
            )
        features.append(
            Feature(
                number=title.group(1),
                title=title.group(2),
                phase=phase.group(1).strip() if phase else "—",
                status=status.group(1).strip(),
                path=path.name,
            )
        )
    return features


def render(features: list[Feature]) -> str:
    delivered = sum(1 for f in features if f.delivered)
    lines = [
        "# Feature Requirement Documents (FRDs)",
        "",
        "<!-- Generated by tools/features_index.py — edit the FRD headers, not this file. -->",
        "",
        "One document per feature: what it must do, why, and how it was verified. **The status in",
        "each FRD's own header is the single source** — this index is generated from those headers",
        "and a test fails when they disagree, because feature status kept in two places is feature",
        "status that goes stale in the copy nobody opens.",
        "",
        f"**{delivered} of {len(features)} delivered.** Narrative history: [`../DEVLOG.md`]"
        "(../DEVLOG.md). Decisions: [`../adr/`](../adr/README.md). Rules this project has paid"
        " for: [`../LESSONS.md`](../LESSONS.md).",
        "",
        "| FRD | Feature | Phase | Status |",
        "| --- | ------- | ----- | ------ |",
    ]
    for f in features:
        mark = "✅" if f.delivered else "○"
        lines.append(f"| [{f.number}]({f.path}) | {f.title} | {f.phase} | {mark} {f.status} |")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    text = render(read())
    if "--write" in argv:
        INDEX.write_text(text)
        print(f"wrote {INDEX.relative_to(ROOT)}")
    else:
        print(text)
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main(sys.argv[1:]))
