"""An upstream that is free, fast and **declares its own latency** (`FRD-136` FR-1).

A load test against a real model measures the model. A load test against a mock that answers in
zero time measures nothing about holding three hundred open streams. This is the third thing: an
OpenAI-compatible endpoint whose time to first token and token rate are declared in
`tools/loadtest/models.py`, so the gateway's own cost is what remains when they are subtracted.

**A plain ASGI application, not FastAPI**, and the reason is the whole design: the double must be
cheaper per request than the thing under test, or the run measures the double. So there is no
routing table, no validation, no dependency injection; the SSE chunks are pre-encoded bytes chosen
by index, and a streamed answer costs one dictionary lookup and one `asyncio.sleep` per event.

It contacts nothing, needs no credential, and answers the three paths
`upstreams/openai/routes.py` addresses:

    GET  /v1/models
    POST /v1/chat/completions      (streamed and not)
    POST /v1/embeddings

Run it directly for a baseline, or in the stack with `make loadtest-up`:

    uv run uvicorn tools.loadtest.modelsim:app --host 0.0.0.0 --port 8099
"""

from __future__ import annotations

import asyncio
import json
import os
import time
from typing import Any

from tools.loadtest.models import (
    BY_NAME,
    CHAT_MODELS,
    EMBEDDING_BY_NAME,
    EMBEDDING_MODELS,
    TOOL_CALL_TOKENS,
    TOOL_MARKER,
    SimModel,
)

#: How many pre-encoded chunk bodies each model keeps. The content differs between them only so
#: that a run cannot accidentally measure a compressor noticing a repeated string; 64 is enough
#: for that and small enough to build at import.
_CHUNK_POOL = 64

#: The words the double answers with. Deliberately dull: an answer nobody would mistake for a
#: model's, in a request log that will sit in a development database afterwards.
_VOCABULARY = (
    "simulated token from the load double",
    "this text is generated by a stub",
    "no model produced this sentence",
    "placeholder output for capacity testing",
)

#: Characters per token, for counting a prompt. Not a tokenizer: what the counts have to be is
#: *stable and proportional*, because the figures they feed — budget reservations, the cost
#: column — are being exercised, not verified, by a load run.
_CHARS_PER_TOKEN = 4

#: What a `sim-instant` answer must not do: sleep. Zero is a legitimate configuration and
#: `asyncio.sleep(0)` still yields to the loop, which at 300 streams is thousands of needless
#: reschedules per second.
_NO_DELAY = 0.0

#: Set to a float to add that many seconds to every response — a lever for showing that the
#: gateway's own cost does not grow with the upstream's.
EXTRA_LATENCY = float(os.environ.get("MODELSIM_EXTRA_LATENCY", "0") or 0)


def _token_words(count: int) -> str:
    """``count`` whitespace-separated words, which is what the double calls a token."""
    if count <= 0:
        return ""
    words = " ".join(_VOCABULARY)
    pool = words.split()
    return " ".join(pool[index % len(pool)] for index in range(count))


class _Chunks:
    """One model's pre-encoded SSE events.

    Built once, at import. Everything that varies per request — the finish reason, the usage —
    lives in the two events at the end, which are the only ones built per request.
    """

    __slots__ = ("content", "reasoning", "role")

    def __init__(self, model: SimModel) -> None:
        self.role = _sse({"choices": [{"index": 0, "delta": {"role": "assistant"}}]}, model.name)
        pool = " ".join(_VOCABULARY).split()
        self.content = [
            _sse(
                {
                    "choices": [
                        {
                            "index": 0,
                            "delta": {
                                "content": " "
                                + " ".join(
                                    pool[(index + offset) % len(pool)]
                                    for offset in range(model.tokens_per_chunk)
                                )
                            },
                        }
                    ]
                },
                model.name,
            )
            for index in range(_CHUNK_POOL)
        ]
        self.reasoning = [
            _sse(
                {
                    "choices": [
                        {
                            "index": 0,
                            "delta": {
                                "reasoning": " "
                                + " ".join(
                                    pool[(index + offset) % len(pool)]
                                    for offset in range(model.tokens_per_chunk)
                                )
                            },
                        }
                    ]
                },
                model.name,
            )
            for index in range(_CHUNK_POOL)
        ]


def _sse(payload: dict[str, Any], model: str) -> bytes:
    body = {"id": "simcmpl", "object": "chat.completion.chunk", "model": model, **payload}
    return b"data: " + json.dumps(body, separators=(",", ":")).encode() + b"\n\n"


_CHUNKS: dict[str, _Chunks] = {model.name: _Chunks(model) for model in CHAT_MODELS}

_DONE = b"data: [DONE]\n\n"


def _prompt_tokens(body: dict[str, Any]) -> int:
    """Count the prompt the way a model would bill it: everything sent, not just the last turn."""
    total = 0
    for message in body.get("messages") or ():
        content = message.get("content")
        if isinstance(content, str):
            total += len(content)
        elif isinstance(content, list):
            for part in content:
                if isinstance(part, dict):
                    total += len(str(part.get("text") or ""))
                    # An image's base64 is real bytes on the wire and real prompt tokens.
                    url = (part.get("image_url") or {}).get("url", "")
                    total += len(url) // 3
        for call in message.get("tool_calls") or ():
            total += len(json.dumps(call))
    for tool in body.get("tools") or ():
        total += len(json.dumps(tool))
    return max(1, total // _CHARS_PER_TOKEN)


def _wants_tool_call(body: dict[str, Any]) -> bool:
    """Whether the driver asked for a tool call, through the only channel that survives.

    The marker travels in the prompt because the canonical mapping carries the prompt and drops
    everything it does not know — a header or an invented body field would arrive nowhere, and a
    switch that silently does nothing is worse than no switch.
    """
    if not body.get("tools"):
        return False
    for message in reversed(body.get("messages") or ()):
        content = message.get("content")
        if isinstance(content, str) and TOOL_MARKER in content:
            return True
    return False


def _output_plan(model: SimModel, body: dict[str, Any], *, tool_call: bool) -> tuple[int, int]:
    """How many tokens of answer and of thinking this response will carry.

    The arithmetic lives on `SimModel` so the driver subtracts the same figure the double sleeps
    (`FRD-136` FR-5). `reasoning_effort: "none"` is the caller switching thinking off, and a
    double that thought anyway would make `FRD-111`'s control untestable under load.
    """
    asked = body.get("max_tokens")
    answer, reasoning = model.plan(
        int(asked) if isinstance(asked, int) else None,
        thinking=body.get("reasoning_effort") != "none",
    )
    # A turn that ends in a tool call stops generating prose.
    return (TOOL_CALL_TOKENS if tool_call else answer), reasoning


def _usage(prompt: int, completion: int, reasoning: int) -> dict[str, Any]:
    return {
        "prompt_tokens": prompt,
        "completion_tokens": completion + reasoning,
        "total_tokens": prompt + completion + reasoning,
        # Inside `completion_tokens`, which is what this dialect does and what
        # `mapping/response.py` reads (`FRD-135` FR-1).
        "completion_tokens_details": {"reasoning_tokens": reasoning},
        "prompt_tokens_details": {"cached_tokens": 0},
    }


def _tool_call_message(content: str) -> dict[str, Any]:
    return {
        "role": "assistant",
        "content": content or None,
        "tool_calls": [
            {
                "id": "simcall-1",
                "type": "function",
                "function": {
                    "name": "read_file",
                    "arguments": json.dumps({"path": "src/main.py"}),
                },
            }
        ],
    }


async def _chat(body: dict[str, Any], send: Any) -> None:
    name = str(body.get("model") or "")
    model = BY_NAME.get(name)
    if model is None:
        await _json(send, 404, {"error": {"message": f"No such model '{name}'."}})
        return

    prompt = _prompt_tokens(body)
    tool_call = _wants_tool_call(body)
    answer_tokens, reasoning_tokens = _output_plan(model, body, tool_call=tool_call)
    if body.get("stream"):
        await _stream(model, body, send, prompt, answer_tokens, reasoning_tokens, tool_call)
        return

    await _sleep(model.declared_seconds(answer_tokens, reasoning_tokens) + EXTRA_LATENCY)
    message: dict[str, Any] = (
        _tool_call_message(_token_words(answer_tokens))
        if tool_call
        else {"role": "assistant", "content": _token_words(answer_tokens)}
    )
    if reasoning_tokens:
        message["reasoning"] = _token_words(reasoning_tokens)
    await _json(
        send,
        200,
        {
            "id": "simcmpl",
            "object": "chat.completion",
            "model": name,
            "choices": [
                {
                    "index": 0,
                    "message": message,
                    "finish_reason": "tool_calls" if tool_call else "stop",
                }
            ],
            "usage": _usage(prompt, answer_tokens, reasoning_tokens),
        },
    )


async def _stream(
    model: SimModel,
    body: dict[str, Any],
    send: Any,
    prompt: int,
    answer_tokens: int,
    reasoning_tokens: int,
    tool_call: bool,
) -> None:
    await send(
        {
            "type": "http.response.start",
            "status": 200,
            "headers": [
                (b"content-type", b"text/event-stream"),
                (b"cache-control", b"no-store"),
            ],
        }
    )
    chunks = _CHUNKS[model.name]
    # **An absolute schedule, not a chain of sleeps.** `asyncio.sleep` overshoots by a fraction of
    # a millisecond every time, and a 600-token answer is 600 sleeps: measured here at ~1.2 ms of
    # overshoot per event, which is 0.7 s the double would have spent and the gateway would have
    # been charged for. `Clock` sleeps until a *deadline* computed from the start, so a late event
    # is caught up rather than accumulated, and the double's own slowness under load shows as the
    # stream finishing on time with its events bunched — not as gateway latency.
    clock = _Clock(model.ttft_ms / 1000.0 + EXTRA_LATENCY)
    await clock.wait()
    await send({"type": "http.response.body", "body": chunks.role, "more_body": True})

    per_chunk = max(1, model.tokens_per_chunk)
    gap = model.seconds_per_chunk

    # Thinking first, then the answer — the order a reasoning model emits them in, and the reason
    # time to first *visible* token is not time to first event (`FRD-135`).
    for index in range((reasoning_tokens + per_chunk - 1) // per_chunk):
        await clock.advance(gap)
        body_bytes = chunks.reasoning[index % _CHUNK_POOL]
        await send({"type": "http.response.body", "body": body_bytes, "more_body": True})

    if tool_call:
        # The call's own tokens are waited for before it is emitted, so that a tool turn takes the
        # time `SimModel.declared_seconds` promises for it. Sent as one delta afterwards, which is
        # the shape `StreamedToolCalls` reassembles (`FRD-131` FR-6).
        for _ in range(-(-answer_tokens // per_chunk)):
            await clock.advance(gap)
        await send(
            {
                "type": "http.response.body",
                "body": _sse(
                    {
                        "choices": [
                            {
                                "index": 0,
                                "delta": {
                                    "tool_calls": [
                                        {
                                            "index": 0,
                                            "id": "simcall-1",
                                            "type": "function",
                                            "function": {
                                                "name": "read_file",
                                                "arguments": '{"path": "src/main.py"}',
                                            },
                                        }
                                    ]
                                },
                            }
                        ]
                    },
                    model.name,
                ),
                "more_body": True,
            }
        )
    else:
        for index in range((answer_tokens + per_chunk - 1) // per_chunk):
            await clock.advance(gap)
            body_bytes = chunks.content[index % _CHUNK_POOL]
            await send({"type": "http.response.body", "body": body_bytes, "more_body": True})

    finish = _sse(
        {
            "choices": [
                {"index": 0, "delta": {}, "finish_reason": "tool_calls" if tool_call else "stop"}
            ]
        },
        model.name,
    )
    await send({"type": "http.response.body", "body": finish, "more_body": True})
    # The usage-only event: empty `choices`, which is the shape `openai_chunk_to_canonical` reads
    # and the only reason a streamed request is settled rather than released (`FRD-405`).
    usage = _sse(
        {"choices": [], "usage": _usage(prompt, answer_tokens, reasoning_tokens)}, model.name
    )
    await send({"type": "http.response.body", "body": usage, "more_body": True})
    await send({"type": "http.response.body", "body": _DONE, "more_body": False})


async def _embed(body: dict[str, Any], send: Any) -> None:
    name = str(body.get("model") or "")
    model = EMBEDDING_BY_NAME.get(name)
    if model is None:
        await _json(send, 404, {"error": {"message": f"No such model '{name}'."}})
        return
    texts = body.get("input")
    if isinstance(texts, str):
        texts = [texts]
    texts = list(texts or [])
    dimensions = int(body.get("dimensions") or model.dimensions)
    await _sleep((model.base_ms + model.ms_per_text * len(texts)) / 1000.0 + EXTRA_LATENCY)
    # One vector, reused by reference. The bytes on the wire are identical either way, and
    # building 256 distinct float lists would put the double's own allocation into the measurement.
    vector = [0.0123] * dimensions
    prompt = sum(len(str(text)) for text in texts) // _CHARS_PER_TOKEN
    await _json(
        send,
        200,
        {
            "object": "list",
            "model": name,
            "data": [
                {"object": "embedding", "index": index, "embedding": vector}
                for index in range(len(texts))
            ],
            "usage": {"prompt_tokens": max(1, prompt), "total_tokens": max(1, prompt)},
        },
    )


class _Clock:
    """A schedule measured from one start, so a stream's events do not drift.

    Every `asyncio.sleep` returns a little late. Chained, those fractions become the difference
    between what the double promised and what it delivered — and that difference is exactly what
    `FRD-136` FR-5 attributes to the gateway. Deadlines cannot drift: a late event shortens the
    next wait instead of pushing it.
    """

    __slots__ = ("_due",)

    def __init__(self, first: float) -> None:
        self._due = time.monotonic() + first

    async def wait(self) -> None:
        remaining = self._due - time.monotonic()
        if remaining > _NO_DELAY:
            await asyncio.sleep(remaining)

    async def advance(self, gap: float) -> None:
        self._due += gap
        await self.wait()


async def _sleep(seconds: float) -> None:
    if seconds > _NO_DELAY:
        await asyncio.sleep(seconds)


async def _json(send: Any, status: int, payload: dict[str, Any]) -> None:
    body = json.dumps(payload, separators=(",", ":")).encode()
    await send(
        {
            "type": "http.response.start",
            "status": status,
            "headers": [
                (b"content-type", b"application/json"),
                (b"content-length", str(len(body)).encode()),
            ],
        }
    )
    await send({"type": "http.response.body", "body": body})


async def _read_body(receive: Any) -> bytes:
    chunks: list[bytes] = []
    while True:
        message = await receive()
        chunks.append(message.get("body", b""))
        if not message.get("more_body"):
            return b"".join(chunks)


_LISTING = {
    "object": "list",
    "data": [
        {"id": model.name, "object": "model", "owned_by": "modelsim"}
        for model in (*CHAT_MODELS, *EMBEDDING_MODELS)
    ],
}

_STARTED = time.monotonic()


async def app(scope: dict[str, Any], receive: Any, send: Any) -> None:
    if scope["type"] == "lifespan":
        while True:
            message = await receive()
            if message["type"] == "lifespan.startup":
                await send({"type": "lifespan.startup.complete"})
            elif message["type"] == "lifespan.shutdown":
                await send({"type": "lifespan.shutdown.complete"})
                return
        return
    if scope["type"] != "http":
        return

    path = scope["path"]
    if path == "/v1/models":
        await _json(send, 200, _LISTING)
        return
    if path == "/healthz":
        await _json(send, 200, {"status": "ok", "uptime_s": round(time.monotonic() - _STARTED, 1)})
        return

    raw = await _read_body(receive)
    try:
        body = json.loads(raw) if raw else {}
    except ValueError:
        await _json(send, 400, {"error": {"message": "Body is not JSON."}})
        return

    if path == "/v1/chat/completions":
        await _chat(body, send)
    elif path == "/v1/embeddings":
        await _embed(body, send)
    else:
        await _json(send, 404, {"error": {"message": f"No such path '{path}'."}})
