# Generated by Django 6.0.7 on 2026-08-09 15:05

from typing import Any

from django.db import migrations, models


def retire_duplicate_positions(apps: Any, schema_editor: Any) -> None:
    """Retire questions a rename left behind, keeping the ones the catalogue now declares.

    Before this migration the seed keyed questions on `topic`, so renaming one created a second
    question at the same position while the original kept its answers. Two rows then share a
    position, which the new constraint forbids — and picking which to keep is not arbitrary: the
    **newest** row is what the current catalogue declares, and the older one is retired rather than
    deleted so the verdicts already given against its wording survive.
    """
    TestCase = apps.get_model("smoketests", "TestCase")
    seen: set[tuple[int, int]] = set()
    for case in TestCase.objects.order_by("battery_id", "position", "-id"):
        key = (case.battery_id, case.position)
        if key in seen:
            case.retired = True
            case.save(update_fields=["retired"])
        else:
            seen.add(key)


class Migration(migrations.Migration):
    dependencies = [
        ("smoketests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="retired",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(retire_duplicate_positions, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="testcase",
            constraint=models.UniqueConstraint(
                condition=models.Q(("retired", False)),
                fields=("battery", "position"),
                name="unique_position_per_battery",
            ),
        ),
    ]
